"""add phone number to the user

Revision ID: 624dfb514572
Revises: c03bbd47aa8f
Create Date: 2022-04-04 00:06:46.442051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624dfb514572'
down_revision = 'c03bbd47aa8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
